replicas: 1
minimumMasterNodes: 1
image: "docker.io/library/elasticsearch"
imageTag: "8.5.3"
ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
    #kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
  className: ""
  enabled: true
  pathtype: ImplementationSpecific
  hosts:
    - host: es.int.proaimltd.com.cn
      paths:
        - path: /
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
secret:
  enabled: true
  password: "proaim@2013"
esConfig:
   elasticsearch.yml: |
       http.cors.enabled: true
       http.cors.allow-origin: "*"
       http.cors.allow-headers: Authorization,X-Requested-With,Content-Length,Content-Type
       xpack.ml.enabled: false
       xpack.security.enabled: true
       xpack.security.transport.ssl.enabled: true

persistence:
  enabled: false
