replicas: 1
image: "docker.io/library/kibana"
imageTag: "8.5.1"
ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
  className: ""
  enabled: true
  pathtype: Prefix
  hosts:
    - host: kibana.int.proaimltd.com.cn
      paths:
        - path: /
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
